name: mind_care
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  responsive_sizer: ^3.3.1
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  http: ^1.3.0
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  uuid: ^4.5.1
  flutter_chat_bubble: ^2.0.2
  flutter_markdown: ^0.7.6+2
  flutter_launcher_icons: ^0.14.3
  font_awesome_flutter: ^10.8.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.2.2
  shared_preferences: ^2.5.2
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  intl: ^0.20.2
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  image_path_android: "assets/images/launch_icon.png"
  image_path_ios: "assets/images/launch_icon.png"
  android: true
  ios: true
  adaptive_icon_background: "assets/images/launch_icon.png"
  adaptive_icon_foreground: "assets/images/launch_icon.png"
  adaptive_icon_foreground_inset: 16
  adaptive_icon_monochrome: "assets/images/launch_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
